import './js/about-me';
import './js/benefits';
import './js/covers';
import './js/faq';
import './js/header';
import './js/hero';
import './js/mob-menu';
import './js/projects';
import './js/work-together';
